/// Specific error codes for HRX protocol operations.
enum HrxErrorCode {
  invalidQr,
  unknownProtocol,
  unsupportedVersion,
  invalidPacket,
  invalidSignature,
  integrityFailure,
  decryptionFailure,
  decompressionFailure,
  deserializationFailure,
  invalidSchema,
  missingField,
  payloadTooLarge,
  unknownKey,
}

/// Strongly-typed exception class for HRX protocol operations with user-friendly messages.
class HrxException implements Exception {
  final HrxErrorCode code;
  final String message;
  final String userFriendlyMessage;
  final dynamic details;

  HrxException({
    required this.code,
    required this.message,
    String? userFriendlyMessage,
    this.details,
  }) : userFriendlyMessage = userFriendlyMessage ?? _defaultUserMessage(code);

  static String _defaultUserMessage(HrxErrorCode code) {
    switch (code) {
      case HrxErrorCode.invalidQr:
        return 'The scanned QR code is invalid or could not be recognized as a medical record.';
      case HrxErrorCode.unknownProtocol:
        return 'Unsupported medical QR format. Please verify the code was generated by an authorized health app.';
      case HrxErrorCode.unsupportedVersion:
        return 'Unsupported QR protocol version. Please update the application to read newer record formats.';
      case HrxErrorCode.invalidPacket:
        return 'The medical record packet format is corrupted or incomplete.';
      case HrxErrorCode.invalidSignature:
      case HrxErrorCode.integrityFailure:
        return 'Security Alert: Record verification failed. The QR code appears to have been altered or corrupted.';
      case HrxErrorCode.decryptionFailure:
        return 'Security Alert: Unable to decrypt medical record. Incorrect encryption key or data corruption.';
      case HrxErrorCode.decompressionFailure:
        return 'Record data decompression failed. The payload may be truncated.';
      case HrxErrorCode.deserializationFailure:
        return 'Failed to parse structured medical record data.';
      case HrxErrorCode.invalidSchema:
      case HrxErrorCode.missingField:
        return 'Medical record schema is invalid or missing essential clinical fields.';
      case HrxErrorCode.payloadTooLarge:
        return 'This visit record is too large to fit in a single QR code. Reduce data or use digital transfer.';
      case HrxErrorCode.unknownKey:
        return 'Unknown encryption key ID. The record was encrypted with an unrecognized authority key.';
    }
  }

  @override
  String toString() => 'HrxException($code): $message';
}
